### ISSUE TITLE
Enable all CLI commands only after starting the peer

### ISSUE THREAD

**Issue by adrelanos** [AnemoneLabs/unmessage#27]
`/req-send redacted redacted` failed for me.
```
> Exception in thread Thread-2:
                               Traceback (most recent call last):
                                                                   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                                                                                                             self.run()
                                                                                                                                                         File "/usr/lib/python2.7/threading.py", line 754, in run
                                                       self.__target(*self.__args, **self.__kwargs)
                                                                                                     File "/home/user/unmessage/unmessage/peer.py", line 684, in _send_request
                    req = self._create_request(contact)
                                                         File "/home/user/unmessage/unmessage/peer.py", line 283, in _create_request
                                                                                                                                        b2a(self.identity_keys.pub),
      AttributeError: 'NoneType' object has no attribute 'pub'
```

**Comment by felipedau** [comment]
Hmm, this might be one of those cases which `peer.info` was not saved properly because unMessage failed to start on our previous tests. You peer's identity keypair does not seem to exist. `~/.config/unMessage/<peer_name>/peer.info` should have:

```
BEGIN TRANSACTION;
CREATE TABLE contacts (
                    identity TEXT,
                    key TEXT,
                    is_verified INTEGER,
                    has_presence INTEGER);
CREATE TABLE peer (
                    name TEXT,
                    port_local_server INTEGER,
                    priv_identity_key TEXT,
                    pub_identity_key TEXT,
                    onion_service_key TEXT);
INSERT INTO "peer" VALUES('<peer_name>',50000,'<priv_key>','<pub_key>','RSA1024:<onion_service_key>');
CREATE UNIQUE INDEX peer_name
            ON
                peer (name);
CREATE UNIQUE INDEX contact_identity
            ON
                contacts (identity);
COMMIT;
```

I believe that by creating a peer with another name or `rm -fr ~/.config/unMessage/` and re-creating it should work because now unMessage will start successfully.

I am going to use this ticket to manage the fix for all these problems we had with a corrupted info file.

Thanks!

**Comment by adrelanos** [comment]
My unMessage startup command is actually this one.

1)

    rm -fr ~/.config/unMessage/ && unmessage-cli -n n --local-server-ip $(qubesdb-read /qubes-ip) --connect-to-tor -c 9151 -t 9050

2) get the python exception from my original post in this issue
3) kill unMessage
4) there is no file `~/.config/unMessage/<peer_name>/peer.info`

**Comment by felipedau** [comment]
On Thu, Mar 09, 2017 at 06:13:56AM -0800, Patrick Schleizer wrote:
> My unMessage startup command is actually this one.
> 
> 1)
> 
>     rm -fr ~/.config/unMessage/ && unmessage-cli -n n --local-server-ip $(qubesdb-read /qubes-ip) --connect-to-tor -c 9151 -t 9050
> 
> 2) get the python exception from my original post in this issue
> 3) kill unMessage
> 4) there is no file `~/.config/unMessage/<peer_name>/peer.info`

Oh, I think I know what is going on. It does not look like unMessage
has started completely. When unMessage *is still launching*, this is
what will be displayed:

```
 * unMessage
 
 * Starting peer
 * Configuring local server
 * Running local server
 * Connecting to existing Tor
 * Running reactor
 * Controlling Tor process
 * Waiting for the Onion Service
```

Onion services are usually created <30 seconds, so that's how long
you might have to wait. Once it is created, the screen will be
refreshed to:

```
 * unMessage - <peer>@domain.onion:50000 <public_key>


 * There are no conversations
```

That's the "main screen" where you can send commands. I believe the
issue here is that unMessage allows all commands to be sent while it
is still starting and that's why you do not have a keypair yet. That
may not be very clear in the
[CLI docs](https://unmessage.readthedocs.io/en/latest/cli/cli.html)
:/

If you wait for a minute and unMessage does not display the main
screen, then there was some issue when asking Tor to create the hs
and you are stuck in that screen.

Another thing: `peer.info` was the old name of that file. The correct
name is actually `peer.db`. If you are able to successfully start
unMessage, instead of "killing" or closing the window, make sure to
`/quit` to save that file (that should be simplified once #7 is
closed). You may want to check the contents of `peer.db` and confirm
that your keys were properly saved. Also, if you do launch/close it
successfully, make sure to *not* run `rm -fr ~/.config/unMessage/` the
next time you launch it. It should not fail to start anymore and now
you have a peer ready to chat which you might want to persist.

I am still having issues with my Whonix 14 vms, so I haven't been able
to go as far as you went. I will make a couple more tests and let you
know what is going wrong.

Thanks @adrelanos, and sorry for the inconvenience :/

**Comment by adrelanos** [comment]
To avoid killing it, I made a suggestion here:
https://github.com/AnemoneLabs/unmessage/issues/28

I'd also highly recommend unMessage being capable to recover from messed up profiles. Power loss happens and it would not be great if users could not start unMesage then.
