### ISSUE TITLE
Friend of a friend asynchronous message caching

### ISSUE THREAD

**Issue by HulaHoopWhonix** [AnemoneLabs/unmessage#41]
@felipedau
 
Since modern double ratchet protocols are designed for asynchronous chat and you mentioned having to balance between privacy and anonymity in the thread - what if you design unmessage clients to optionally act as opportunistic message stores for their peers (like Retroshare) so recipients can still get their messages sooner even if the sender is offline.

Considerations:

* It would be optional.

* People would be caching for friend of a friend degrees of separation only.

* You would probably allow user configurable limits for the store so people don't arbitrarily flood storage.

* Use pqcrypto (Codecrypt crypto suite) to protect messages stored on third party disks so communication protection is complete when Tor switches to PQ.

**Comment by HulaHoopWhonix** [comment]
Sorry closing as duplicate of https://github.com/AnemoneLabs/unmessage/issues/32

**Comment by felipedau** [comment]
Hi @HulaHoopWhonix!

This not a complete duplicate of #32 but it does try to solve the same problem. Issues I see with this approach are:

- There has to be some kind of agreement between the peers involved because your friend is disclosing their friend's unMessage identity, which also implies that even after an agreement, there must also be some kind of revocation in case they do not wish to do that anymore (this feature may become very complex)
- This might also pose a high risk for anonymity from a higher level because an offline message in the end is linking users and it starts to look like a graph? This obviously requires a very powerful adversary to observe these things, but maybe preventing that is ideal
- Once more people start using it, I believe there is a higher chance of friends sharing the same timezone and in the end it might not solve the problem

Sorry for not having a concrete answer, but I think that what is being proposed in #32 might be easier to implement and might not be as risky as this one. I do encourage you to engage in the discussions from that issue so that we find the best solution for this.

Thanks @HulaHoopWhonix!
