### ISSUE TITLE
Multiline messages in the gui are only partially sent

### ISSUE THREAD

**Issue by rxcomm** [AnemoneLabs/unmessage#6]
When a multiline message is entered into the gui message box and either send is clicked or the return key is hit, only the first line of the message is actually sent.

In the cli, the behavior is correct - all lines of the multiline message are sent.

**Comment by felipedau** [comment]
Thanks for reporting it! It does work on the CLI but I am not too
happy about it.

The idea is to send **one** large message with multiple lines, right?
It should be easy to fix that for Tkinter. However, I am not sure
about curses. It interprets each line break as the end of a message,
so it ends up sending multiple single line messages instead of a
multiline one.

Maybe we just need to add a simple conditional in
`_Textbox.do_command` to break the line in the input window but not
trigger `_Textbox.edit`?
